/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package demoService.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the demo service. Represents a row in the &quot;demo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link demoService.model.impl.demoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link demoService.model.impl.demoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see demo
 * @see demoService.model.impl.demoImpl
 * @see demoService.model.impl.demoModelImpl
 * @generated
 */
@ProviderType
public interface demoModel extends BaseModel<demo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a demo model instance should use the {@link demo} interface instead.
	 */

	/**
	 * Returns the primary key of this demo.
	 *
	 * @return the primary key of this demo
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this demo.
	 *
	 * @param primaryKey the primary key of this demo
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the demo ID of this demo.
	 *
	 * @return the demo ID of this demo
	 */
	public int getDemoId();

	/**
	 * Sets the demo ID of this demo.
	 *
	 * @param demoId the demo ID of this demo
	 */
	public void setDemoId(int demoId);

	/**
	 * Returns the demo name of this demo.
	 *
	 * @return the demo name of this demo
	 */
	@AutoEscape
	public String getDemoName();

	/**
	 * Sets the demo name of this demo.
	 *
	 * @param demoName the demo name of this demo
	 */
	public void setDemoName(String demoName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(demoService.model.demo demo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<demoService.model.demo> toCacheModel();

	@Override
	public demoService.model.demo toEscapedModel();

	@Override
	public demoService.model.demo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}